# Generated by Django 4.2.5 on 2023-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='horario',
            new_name='dia',
        ),
    ]
