# Generated by Django 4.2.5 on 2023-10-02 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_horario_materia_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='hora',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
