# Generated by Django 4.2.5 on 2023-10-02 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_materia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='hora',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
